### PR TITLE
Major refactor to make it compatible with ST3

### PR DESCRIPTION
**Pull request by drslump**
Made it compatible with Sublime Text 3 (Python 3). It should work now in ST2 and ST3.

The refactor also separates the logic from the plugin extension points to make the implementation cleaner.

It will automatically reload settings for any open files in the editor if the `.sublime-settings` file is edited in Sublime itself.

### CODE REVIEW

**Comment by davepeck** [comment]
Oh, very nice. Thank you! 

Looking forward to looking at this over the weekend. At first glance, it looks imminently merge-able. ;-)

**Comment by drslump** [comment]
Updated the PR with support for placeholders and error reporting for invalid format when reading settings files.

**Comment by davepeck** [comment]
Thanks! I've added a pull request to the package control channel so this starts to show up in ST3 too.

**Comment by drslump** [comment]
Great! I'm really liking working with per directory settings instead of projects :neckbeard:

**Pull request merged**
